### ISSUE TITLE
Unable to recreate PSNR values.

### ISSUE THREAD

**Issue by TsainGra** [HighVoltageRocknRoll/sr#5]
I am training ESPCN model with DIV2K+Harmonic data for an upscale factor of 4 and testing it on DIV2K test set. My mean PSNR value is around 27, although I was expecting something near 30 or 31. Are there any tweaks that may be required in the model with the current scale factor?

**Comment by HighVoltageRocknRoll** [comment]
> I am training ESPCN model with DIV2K+Harmonic data for an upscale factor of 4 and testing it on DIV2K test set. My mean PSNR value is around 27, although I was expecting something near 30 or 31. Are there any tweaks that may be required in the model with the current scale factor?

With an upscale factor of 4 you losing too much details that ESPCN is unable to recreate thus resulting in worse PSNR. Results in tables are specified for an upscale factor of 2. So there are no model tweaks, you usually get worse results for higher upscale factors.
